import os
import glob
import re

# Configuration
BASE_DIR = "public/project_2025_03"
MANIFEST_PATH = "src/remotion/NewNewsVideo/storyManifest.ts"
CHUNKS = ["chunk_01", "chunk_02", "chunk_03", "chunk_04", "chunk_05", "chunk_06"]
SLOTS_PER_CHUNK = 20

def main():
    print("Generating Manifest from existing chunk directories...")
    
    manifest_data = {} # chunk_id -> list of filenames (length 20)

    for chunk_id in CHUNKS:
        chunk_path = os.path.join(BASE_DIR, chunk_id)
        
        # Initialize list with empty strings
        chunk_files = [""] * SLOTS_PER_CHUNK
        
        if not os.path.exists(chunk_path):
            print(f"Warning: Directory {chunk_id} does not exist.")
            manifest_data[chunk_id] = chunk_files
            continue

        # Get all png files
        files = glob.glob(os.path.join(chunk_path, "scene_*.png"))
        
        present_indices = []
        
        for file_path in files:
            filename = os.path.basename(file_path)
            # Pattern matching: scene_01_something.png or scene_1.png
            # Look for the first block of digits after "scene_"
            match = re.search(r"scene_(\d+)", filename)
            if match:
                idx = int(match.group(1))
                if 1 <= idx <= SLOTS_PER_CHUNK:
                    # Array is 0-indexed, so idx-1
                    chunk_files[idx-1] = f"project_2025_03/{chunk_id}/{filename}"
                    present_indices.append(idx)
                else:
                    print(f"[{chunk_id}] Ignored file with out-of-range index: {filename}")
            else:
                print(f"[{chunk_id}] Ignored file with bad format: {filename}")

        manifest_data[chunk_id] = chunk_files
        
        # Report missing
        missing = [i for i in range(1, SLOTS_PER_CHUNK + 1) if i not in present_indices]
        if missing:
            print(f"[{chunk_id}] Missing slots: {missing}")
        else:
            print(f"[{chunk_id}] Complete.")

    # Write Manifest TS file
    with open(MANIFEST_PATH, "w") as f:
        f.write("// Auto-generated by organize_assets.py from existing files\n")
        f.write("export const STORY_MANIFEST: Record<string, string[]> = {\n")
        for cid in CHUNKS:
            files = manifest_data.get(cid, [])
            f.write(f'  "{cid}": [\n')
            for file_path in files:
                f.write(f'    "{file_path}",\n')
            f.write("  ],\n")
        f.write("};\n")
    
    print(f"Manifest written to {MANIFEST_PATH}")

if __name__ == "__main__":
    main()
